# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'VehicleLookup' do

pod 'SignalR-ObjC'

end

target 'VehicleLookupTests' do

end

